#!/usr/bin/env bash
## Write good luck on line 8 and bad luck on line 4

line=0

while [$line -lt 10]
do
	if [$line -eq 4]
	then
		echo "bad luck"
	elif [$line -eq 8]
	then
		echo "good luck"
	else 
		echo "Best School"
	fi
	(( $line++ ))
done
