#!/usr/bin/env bash
###Write a Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.

line=0

while [$line -lt 10]
do
	if [$line -eq 4]
	then
		echo "bad luck"
	elif [$line -eq 8]
	then
		echo "good luck"
	else 
		echo "Best School"
	fi
	(( $line++ ))
done
