#!/usr/bin/env bash
##display hours and minutes 0-12:1-59

Hour=0

while (( Hour <= 12 )); do
		echo "Hour: $Hour"
number=1
	while (( minute <= 59 )); do
		echo "$minute"	
	(( minute++ ))
	done
	(( Hour++ ))i
done
