#!/usr/bin/env bash
##display hours and minutes 0-12:1-59

Hour=0
minutue=1

while (( Hour <= 12 )); do
		echo "Hour: $Hour"
	if (( minute <= 59 )); then
		echo "$minute"	
	(( minute++ ))
	fi
	(( Hour++ ))
done
