#!/usr/bin/env bash
##looking for file if empty or exists

file=school

if [ -f "$file" ]; then
	echo "school file exists"
	if [ ! -s "$file" ]; then
		echo "school file does not exist"
	else
		echo "school file is not empty"
	fi

	if [ -e "file" ] && [! -L "file" ]; then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
